# Generated by Django 4.0.3 on 2022-04-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
