# Generated by Django 4.0.3 on 2022-04-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_customer_user'),
        ('customer', '0010_alter_customer_user'),
    ]

    operations = [
    ]
