# Generated by Django 4.0.3 on 2022-04-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_sellwaste_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellwaste',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
