# Generated by Django 4.0.3 on 2022-04-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_sellwaste_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellwaste',
            name='pickup_address',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
