# Generated by Django 4.0.3 on 2022-04-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_sellwaste_is_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellwaste',
            name='pickup_point',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
