# Generated by Django 4.0.3 on 2022-04-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_sellwaste_pickup_address'),
        ('ecommerce', '0007_sellwaste_pickup_point'),
    ]

    operations = [
    ]
