# Generated by Django 4.0.3 on 2022-04-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_remove_sellwaste_pickup_point_alter_sellwaste_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellwaste',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sellwaste',
            name='is_admins',
            field=models.BooleanField(default=False),
        ),
    ]
