# Generated by Django 4.0.3 on 2022-04-12 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0010_alter_sellwaste_active_alter_sellwaste_is_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellwaste',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
