# Generated by Django 4.0.3 on 2022-04-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_alter_sellwaste_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellwaste',
            name='drop_address',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
