# Generated by Django 4.0.3 on 2022-04-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0003_alter_dealer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='stripe_pub_api',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='stripe_secret_api',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
