# Generated by Django 4.0.3 on 2022-04-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0004_dealer_stripe_pub_api_dealer_stripe_secret_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='stripe_pub_api',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='stripe_secret_api',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
