# Generated by Django 4.0.3 on 2022-04-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0004_dealer_stripe_pub_api_dealer_stripe_secret_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='is_admins',
            field=models.BooleanField(default=False),
        ),
    ]
