# Generated by Django 4.0.3 on 2022-04-11 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0005_dealer_is_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='is_admins',
        ),
    ]
