# Generated by Django 4.0.3 on 2022-04-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0006_remove_dealer_is_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
