# Generated by Django 4.0.3 on 2022-04-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0005_alter_dealer_stripe_pub_api_and_more'),
        ('dealer', '0007_dealer_email'),
    ]

    operations = [
    ]
