# Generated by Django 4.0.3 on 2022-04-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0008_merge_20220411_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='email',
        ),
        migrations.AlterField(
            model_name='dealer',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
