# Generated by Django 4.0.3 on 2022-04-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0009_remove_dealer_email_alter_dealer_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='stripe_pub_api',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='stripe_secret_api',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
